name: Reusable TypeScript Type Checker

on:
  workflow_call:
    inputs:
      package-manager:
        description: "Package manager to use (npm, yarn, pnpm)"
        required: false
        type: string
        default: "npm"

permissions:
  contents: read

jobs:
  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ inputs.package-manager }}-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: |
          set -e
          if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
            echo "Installing pnpm and dependencies..."
            npm install -g pnpm
            pnpm install --frozen-lockfile
          elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
            echo "Installing yarn and dependencies..."
            npm install -g yarn
            yarn install --frozen-lockfile
          else
            echo "Installing npm dependencies..."
            npm ci
          fi

      - name: Run TypeScript type checking
        run: |
          echo "Running TypeScript type checking..."
          if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
            pnpm exec tsc --noEmit
          elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
            yarn exec tsc --noEmit
          else
            npx tsc --noEmit
          fi
          echo "✅ TypeScript type checking passed!"
