name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    name: Code Formatting Check
    uses: ./.github/workflows/quality-format.yml
    with:
      package-manager: "pnpm"
      format-check-command: "pnpm run format:check"
      format-fix-command: "pnpm run format"
    secrets:
      workflow-token: ${{ secrets.GITHUB_TOKEN }}
