# Generate a debug APK for an Android project using customizable inputs.

name: Build Debug APK

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version to use for building"
        required: false
        type: string
        default: '17'
      java-distribution:
        description: "Java distribution to use"
        required: false
        type: string
        default: 'oracle'
      gradle-cache:
        description: "Enable Gradle caching"
        required: false
        type: boolean
        default: true
      checkout-ref:
        description: "Git reference to checkout"
        required: false
        type: string
        default: 'main'
      secret-files-artifact-name:
        description: "Name of the secret files artifact to download"
        required: false
        type: string
        default: ''
      secret-files-path:
        description: "Path where secret files should be extracted"
        required: false
        type: string
        default: './app'
      gradle-build-command:
        description: "Gradle command to build debug APK"
        required: false
        type: string
        default: './gradlew assembleDebug'
      apk-output-path:
        description: "Path to the generated debug APK file"
        required: false
        type: string
        default: 'app/build/outputs/apk/debug/app-debug.apk'
      artifact-name:
        description: "Name for the uploaded APK artifact"
        required: false
        type: string
        default: 'apk-debug'
      artifact-retention-days:
        description: "How long to retain the APK artifact"
        required: false
        type: number
        default: 1

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    name: Build Debug APK
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout-ref }}

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.gradle-cache && 'gradle' || '' }}

      - name: Download secret files
        if: ${{ inputs.secret-files-artifact-name != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.secret-files-artifact-name }}
          path: ${{ inputs.secret-files-path }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ${{ inputs.gradle-build-command }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.apk-output-path }}
          retention-days: ${{ inputs.artifact-retention-days }}