# This workflow checks linting using a specified package manager and command.

name: Lint Checker

on:
  workflow_call:
    inputs:
      package-manager:
        description: "Package manager to use (npm, yarn, pnpm)"
        required: true
        type: string
      lint-check-command:
        description: "Command to check linting"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    outputs:
      needs-lint: ${{ steps.check.outputs.needs-lint }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: Thre4dripper/Reusable-Atomic-Workflows/.github/actions/web-dependencies-setup@main
        with:
          package-manager: ${{ inputs.package-manager }}

      - name: Check linting
        id: check
        run: |
          if ${{ inputs.lint-check-command }}; then
            echo "Code is properly linted."
            echo "needs-lint=false" >> $GITHUB_OUTPUT
          else
            echo "Linting issues found."
            echo "needs-lint=true" >> $GITHUB_OUTPUT
          fi
