name: Unit Tests Worker

on:
  workflow_call:
    inputs:
      package-manager:
        description: "Package manager to use (npm, yarn, pnpm)"
        required: true
        type: string
      test-command:
        description: "Command to run tests"
        required: true
        type: string
      coverage-command:
        description: "Command to generate coverage report"
        required: false
        type: string

    secrets:
      workflow-token:
        description: "GitHub token for authentication"
        required: true

permissions:
  contents: read

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.workflow-token }}

      - name: Setup Dependencies
        uses: ./.github/actions/web-dependencies-setup
        with:
          package-manager: ${{ inputs.package-manager }}

      - name: Run tests
        run: ${{ inputs.test-command }}

      - name: Generate coverage report
        if: inputs.coverage-command != ''
        run: ${{ inputs.coverage-command }}
